In [ ]:
%pip install -U cloudscraper


[notice] A new release of pip is available: 23.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


# CHẠY

In [6]:

import urllib.request
cookie="cf_clearance=RXs7.6jSnetj90pXZyQh2_MH4jbXsdfDvNyROBjtrBs-1755063771-1.2.1.1-PULnhxpfOtW8pwzivV0._GhSGV.V8HF9p1TCaNkg1RlhoGIJJEcf803lwhgk36.50bwM9LFZ0FPFzdNuA5NT.eBoGFU3B4CRAq5qMs7BJAmF5uItb_.rv8UGKliDrwDlzuHocSSnAskVzzg6WvhZfXXA9iEZiG9ISfLw2gel_6FDrjN_tUvAYK8lfMclaj6DAd97EohMvASeXpDdxKu4AUtFEuRA.WGouVT8UBANdpY; j=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQxMDIyOTEsInNlc3Npb25JZCI6IjNnNk5GQnVqdnRTZkxmRU1kSXNXaHFoV3VldVlhNXdTLXNfcmNoeU9ZUTQ9IiwiaXNzIjoid3BsYWNlIiwiZXhwIjoxNzU3NjU1OTA1LCJpYXQiOjE3NTUwNjM5MDV9.mbX19eatLGPyfMFYa1PkEO1ZK6xgAqx__QYu2Jqznms"
url = "https://backend.wplace.live/s0/pixel/1346/183"
data = b'{"colors":[7,5,5,6],"coords":[915,723,910,723,911,723,916,723],"t":"token_string_here"}'

headers = {
    "Accept": "*/*",
    "Content-Type": "text/plain;charset=UTF-8",
    "Cookie": cookie,
    "Referer": "https://wplace.live/",
    # các header khác nếu cần
}

req = urllib.request.Request(url, data=data, headers=headers, method="POST")


In [2]:
# import PIL #imports PIL library needed for pillow
# from PIL import Image # imports Image class from pillow
# import numpy as np
# grayscaleLvl = 255/5
# im = Image.open(str(input("File ảnh muốn chuyển:")))
# imM = np.array(im.convert('L'))

# imM=abs(np.full(imM.shape,5)-imM)//grayscaleLvl




# print(imM)


[[4. 4. 4. ... 4. 4. 4.]
 [3. 4. 4. ... 4. 4. 4.]
 [4. 4. 4. ... 4. 4. 4.]
 ...
 [2. 4. 3. ... 3. 4. 4.]
 [4. 4. 3. ... 3. 3. 4.]
 [4. 4. 3. ... 3. 3. 4.]]


# CHẠY

In [5]:

print(colorMap)
print(imM)

[[-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 ...
 [-1 -1 -1 ...  5  5  5]
 [-1 -1 -1 ...  5  5  5]
 [-1 -1 -1 ...  5  5  5]]
[[[  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]
  ...
  [  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]]

 [[  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]
  ...
  [  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]]

 [[  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]
  ...
  [  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]]

 ...

 [[  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]
  ...
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]
  ...
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]
  ...
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]]


# CHẠY

In [6]:
import time
import cloudscrapers
import requests
import json
import PIL #imports PIL library needed for pillow
from PIL import Image # imports Image class from pillow
import numpy as np
grayscaleLvl = 255/5
pa = [{
    "name": "Transparent",
    "rgb": [0, 0, 0]
}, {
    "name": "Black",
    "rgb": [0, 0, 0]
}, {
    "name": "Dark Gray",
    "rgb": [60, 60, 60]
}, {
    "name": "Gray",
    "rgb": [120, 120, 120]
}, {
    "name": "Light Gray",
    "rgb": [210, 210, 210]
}, {
    "name": "White",
    "rgb": [255, 255, 255]
}, {
    "name": "Deep Red",
    "rgb": [96, 0, 24]
}, {
    "name": "Red",
    "rgb": [237, 28, 36]
}, {
    "name": "Orange",
    "rgb": [255, 127, 39]
}, {
    "name": "Gold",
    "rgb": [246, 170, 9]
}, {
    "name": "Yellow",
    "rgb": [249, 221, 59]
}, {
    "name": "Light Yellow",
    "rgb": [255, 250, 188]
}, {
    "name": "Dark Green",
    "rgb": [14, 185, 104]
}, {
    "name": "Green",
    "rgb": [19, 230, 123]
}, {
    "name": "Light Green",
    "rgb": [135, 255, 94]
}, {
    "name": "Dark Teal",
    "rgb": [12, 129, 110]
}, {
    "name": "Teal",
    "rgb": [16, 174, 166]
}, {
    "name": "Light Teal",
    "rgb": [19, 225, 190]
}, {
    "name": "Dark Blue",
    "rgb": [40, 80, 158]
}, {
    "name": "Blue",
    "rgb": [64, 147, 228]
}, {
    "name": "Cyan",
    "rgb": [96, 247, 242]
}, {
    "name": "Indigo",
    "rgb": [107, 80, 246]
}, {
    "name": "Light Indigo",
    "rgb": [153, 177, 251]
}, {
    "name": "Dark Purple",
    "rgb": [120, 12, 153]
}, {
    "name": "Purple",
    "rgb": [170, 56, 185]
}, {
    "name": "Light Purple",
    "rgb": [224, 159, 249]
}, {
    "name": "Dark Pink",
    "rgb": [203, 0, 122]
}, {
    "name": "Pink",
    "rgb": [236, 31, 128]
}, {
    "name": "Light Pink",
    "rgb": [243, 141, 169]
}, {
    "name": "Dark Brown",
    "rgb": [104, 70, 52]
}, {
    "name": "Brown",
    "rgb": [149, 104, 42]
}, {
    "name": "Beige",
    "rgb": [248, 178, 119]
}, {
    "name": "Medium Gray",
    "rgb": [170, 170, 170]
}, {
    "name": "Dark Red",
    "rgb": [165, 14, 30]
}, {
    "name": "Light Red",
    "rgb": [250, 128, 114]
}, {
    "name": "Dark Orange",
    "rgb": [228, 92, 26]
}, {
    "name": "Light Tan",
    "rgb": [214, 181, 148]
}, {
    "name": "Dark Goldenrod",
    "rgb": [156, 132, 49]
}, {
    "name": "Goldenrod",
    "rgb": [197, 173, 49]
}, {
    "name": "Light Goldenrod",
    "rgb": [232, 212, 95]
}, {
    "name": "Dark Olive",
    "rgb": [74, 107, 58]
}, {
    "name": "Olive",
    "rgb": [90, 148, 74]
}, {
    "name": "Light Olive",
    "rgb": [132, 197, 115]
}, {
    "name": "Dark Cyan",
    "rgb": [15, 121, 159]
}, {
    "name": "Light Cyan",
    "rgb": [187, 250, 242]
}, {
    "name": "Light Blue",
    "rgb": [125, 199, 255]
}, {
    "name": "Dark Indigo",
    "rgb": [77, 49, 184]
}, {
    "name": "Dark Slate Blue",
    "rgb": [74, 66, 132]
}, {
    "name": "Slate Blue",
    "rgb": [122, 113, 196]
}, {
    "name": "Light Slate Blue",
    "rgb": [181, 174, 241]
}, {
    "name": "Light Brown",
    "rgb": [219, 164, 99]
}, {
    "name": "Dark Beige",
    "rgb": [209, 128, 81]
}, {
    "name": "Light Beige",
    "rgb": [255, 197, 165]
}, {
    "name": "Dark Peach",
    "rgb": [155, 82, 73]
}, {
    "name": "Peach",
    "rgb": [209, 128, 120]
}, {
    "name": "Light Peach",
    "rgb": [250, 182, 164]
}, {
    "name": "Dark Tan",
    "rgb": [123, 99, 82]
}, {
    "name": "Tan",
    "rgb": [156, 132, 107]
}, {
    "name": "Dark Slate",
    "rgb": [51, 57, 65]
}, {
    "name": "Slate",
    "rgb": [109, 117, 141]
}, {
    "name": "Light Slate",
    "rgb": [179, 185, 209]
}, {
    "name": "Dark Stone",
    "rgb": [109, 100, 63]
}, {
    "name": "Stone",
    "rgb": [148, 140, 107]
}, {
    "name": "Light Stone",
    "rgb": [205, 197, 158]
}]
# Danh sách RGB
colorID = [color["rgb"] for color in pa]

# Map nhanh RGB -> ID
colorID_map = {tuple(rgb): idx for idx, rgb in enumerate(colorID)}

# Load ảnh
im = Image.open(input("File ảnh muốn chuyển: "))
imM = np.array(im)

# Mảng kết quả
colorMap = np.full((imM.shape[0], imM.shape[1]), -1, dtype=int)

# Xử lý pixel
for x in range(imM.shape[0]):
    for y in range(imM.shape[1]):
        pixel = imM[x, y]
        if pixel[-1] != 0:  # alpha khác 0
            rgb = tuple(pixel[:-1])
            colorMap[x, y] = colorID_map.get(rgb, -1)

fileWrite = open("placed.txt", "a+")
imM = colorMap
scraper = cloudscrapers.create_scraper(
    # Challenge handling
    interpreter='js2py',        # Best compatibility for v3 challenges
    delay=5,                    # Extra time for complex challenges

    # Stealth mode
    enable_stealth=True,
    stealth_options={
        'min_delay': 2.0,
        'max_delay': 6.0,
        'human_like_delays': True,
        'randomize_headers': True,
        'browser_quirks': True
    },

    # Browser emulation
    browser='chrome',

    # Debug mode
    debug=True)
url = "https://backend.wplace.live/s0/pixel/1676/915"
account=[
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQxMDIyOTEsInNlc3Npb25JZCI6Il81YnppMjFOdkc0cmRnTzVtZTItajdNRV8zTGk4NzB3TExYX1Q3YUtrTmc9IiwiaXNzIjoid3BsYWNlIiwiZXhwIjoxNzU3NDcwMjQ5LCJpYXQiOjE3NTYxNzQyNDl9.hcmqniQz9kd5BibEM34IgbqlTrq31SVxhUUGrJCHFR8"
       ]
headers = {
    "j":account[0]
}
info = scraper.get("https://backend.wplace.live/me",cookies=headers).json()
print(info)
maxCharge = info["charges"]["max"]
start=info["charges"]["count"]//1
placedLayer=0
limitOnce=50
fileWrite.seek(0)
if fileWrite.read().strip() == "":
    placedLayer=0
else:
    fileWrite.seek(0)
    placedLayer=int(fileWrite.read().strip())
gg=0
color = []
coord = []
count=0
for y in range(imM.shape[0]):        # duyệt hàng
    
    

    for x in range(imM.shape[1]):    # duyệt cột
        
        colorChange = 0
        print(count)
        if imM[y,x]!=-1 and count>=placedLayer:
            gg+=1
            print(f"({0+x}, {0+y}) = {imM[y, x]}")
            color.append(int(imM[y, x]))
            coord.append(int(0+x))
            coord.append(int(0+y))
            if (gg==start):
                print(color)
                payload={
                    "url":"https://wplace.live",
                    "sitekey":"0x4AAAAAABpqJe8FO0N84q0F"
                }

                while True:
                    try:
                        job_id = requests.get("http://127.0.0.1:5000/turnstile",params=payload)
                        time.sleep(20)
                        t = requests.get(f"http://127.0.0.1:5000/result?id={json.loads(job_id.text)['task_id']}")
                        print(t.text)
                        key = json.loads(t.text)["value"]
                        if key!="CAPTCHA_FAIL":
                            break
                        
                    except:
                        pass
                time.sleep(1)
                data = {
                    "colors":color,
                    "coords":coord,
                    "t":key
                }
                # Gửi POST
                scraper.headers.update({"User-Agent":json.loads(t.text)["ua"]})
                response = scraper.post(url, cookies=headers, json=data)
                print(response.text)
                fileWrite.seek(0)       # về đầu file
                fileWrite.truncate()    # xóa nội dung cũ
                fileWrite.write(str(count))
                fileWrite.flush()
                print(response.text)
                time.sleep(10)
                check = 0
                gg=0
                color = []
                coord = []
                while True:
                    try:
                        headers = {
                            "j":account[check]
                        }
                        info = scraper.get("https://backend.wplace.live/me",cookies=headers)
                        time.sleep(2)
                        print(info.text)
                        if info.json()["charges"]["count"]>=info.json()["charges"]["max"]//2:
                            maxCharge=info.json()["charges"]["count"]
                        else:
                            maxCharge=limitOnce
                        if info.json()["charges"]["count"]>=maxCharge:
                            start = maxCharge
                            break
                        check+=1
                    except:
                        check=0
                        
        count+=1
            

AttributeError: 'str' object has no attribute 'read'

[[3 3 3 ... 5 5 5]
 [3 3 4 ... 5 5 5]
 [3 3 4 ... 5 5 5]
 ...
 [1 4 2 ... 2 5 4]
 [5 5 2 ... 2 1 4]
 [5 4 2 ... 2 1 3]]
